version: '3.8'
services:
  app:
    build: .
    ports:
      - "4000:8000"
    volumes:
      - ./app:/usr/src/app
    env_file:
      - .env
    stdin_open: true
    tty: true
#    command: python main.py
